CREATE TABLE IF NOT EXISTS venue (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  address VARCHAR(255) NOT NULL,
  total_capacity BIGINT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE IF NOT EXISTS event (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  venue_id BIGINT NOT NULL,
  total_capacity BIGINT NOT NULL,
  left_capacity BIGINT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT fk_venue_id FOREIGN KEY (venue_id) REFERENCES venue(id) ON DELETE CASCADE
);
